
name: Test
on: [pull_request]
jobs:
  find-modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get-module-directories
        uses: bendrucker/find-terraform-modules@v1
    outputs:
      matrix: ${{ steps.get-module-directories.outputs.modules }}
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - run: terraform fmt -check -diff -recursive
  validate:
    runs-on: ubuntu-latest
    needs: find-modules
    strategy:
      matrix:
        module: ${{ fromJson(needs.find-modules.outputs.matrix) }}
    defaults:
      run:
        working-directory: ${{ matrix.module }}
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - run: terraform init
      - run: terraform validate
